global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.yandex.ru:587"
  smtp_from: "negatl1lve@yandex.ru"
  smtp_auth_username: "negatl1lve@yandex.ru"
  smtp_auth_password: "__SET_IN_VM__"
  smtp_require_tls: true

route:
  receiver: "email-notifications"
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 3h

receivers:
  - name: "email-notifications"
    email_configs:
      - to: "negatl1lve@yandex.ru"
        send_resolved: true

